name: knowunity_case_study
description: A case study for Knowunity.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # Network
  http: ^1.1.0

  # UI
  animated_line_through: ^1.0.2

  # Utils
  path: ^1.8.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
